### ISSUE TITLE
Bottom sheet has starting position at the bottom of the screen

### ISSUE THREAD

**Issue by tonissimo** [OfTheWolf/UBottomSheet#1]
@OfTheWolf Hi! Thanks for posting this demo! It is a great starting point. My question is:

**I would like the default position of the sheet to be the bottom position, but I could not find a way to do that.**

Some things I tried that did not work:
- Setting `container.frame` in the main ViewController's `viewWillAppear`
- Increasing the container's Top Space constraint in the assistant editor
- In BottomSheetVC: changing `lastLevel` to `.bottom`, and calling `updateBottomSheet()` with `.bottomY` instead of `.middleY`

Maybe it is a combination of all of those things that might work but I could not figure it out :( Let me know if you can give me some pointers. Thanks again, it's a great demo!

**Comment by OfTheWolf** [comment]
Hi @tonissimo, 
Just set self.lastY to self.bottomY instead of middleY. See below:
  ```
  override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.initalFrame = UIScreen.main.bounds
        self.middleY = initalFrame.height * 0.6
        self.bottomY = initalFrame.height - bottomOffset
        self.lastY = self.bottomY
        
        bottomSheetDelegate?.updateBottomSheet(frame: self.initalFrame.offsetBy(dx: 0, dy: self.middleY))
    }
```

**Comment by tonissimo** [comment]
Great, thank you! @OfTheWolf

**Comment by AmyNgithub** [comment]
Hi @OfTheWolf,
I have the same question. I have tried to figure it out by looking at your previous answer, but can't figure out where to place the viewWillAppear function. 

No matter where I try I get errors like:
"Value of type 'MapsDemoBottomSheetController' has no member 'initalFrame'"
"Value of type 'MapsDemoBottomSheetController' has no member 'lastY'; did you mean 'paste'?"
"Use of unresolved identifier 'bottomOffset'; did you mean 'bottomInset'?"
"Use of unresolved identifier 'bottomSheetDelegate'; did you mean 'UIActionSheetDelegate'?"

I get a feeling that you might have rewritten your code since you posted this answer? 

Anyway, Thank you for sharing your code!

**Comment by OfTheWolf** [comment]
Hi @AmyNgithub 
Right I forced committed the new code because i had to create as a new project. So ignore previous comments please. 

BottomSheetController contains snapTo method. Call this in viewdidload after setup methods. I will make it public so it will be accessible in the next release.

you should add the pod files as a source so you can update it.

**Comment by AmyNgithub** [comment]
@OfTheWolf Thank you!

**Comment by OfTheWolf** [comment]
@AmyNgithub calling snapTo in didload didn't work because layout is not ready yet. So i send an update. See below for usage.

```
class MapsDemoBottomSheetController: BottomSheetController{
    override var initialPosition: SheetPosition {
        return .middle
    }
```

**Comment by AmyNgithub** [comment]
@OfTheWolf Works perfectly! Thank you!
