### ISSUE TITLE
Static tableview controller

### ISSUE THREAD

**Issue by mjplanet** [OfTheWolf/UBottomSheet#27]
Static table view controller not scrolling when using UBottomSheetCoordinator.

**Comment by OfTheWolf** [comment]
@mjplanet Can you share video or code please? 

### Possible causes:
UITableViewController may be buggy because of this [line](https://github.com/OfTheWolf/UBottomSheet/blob/master/UBottomSheet/Classes/UBottomSheetCoordinator.swift#L323):
```
public func startTracking<T: DraggableItem>(item: T){
...
        item.view.addGestureRecognizer(pan) 
```

when used with UITableViewController, item.view is UITableView where supposed to be a UIView. You can remove this line or embed your UITableViewController in a container view.

**Comment by mjplanet** [comment]
Embedding UITableViewController in a container view fix this issue. thanks.
