### ISSUE TITLE
How do I implement sheetPositions in SheetViewController?

### ISSUE THREAD

**Issue by GerdC** [OfTheWolf/UBottomSheet#39]
In my SheetViewController I copied the default implementations of `UBottomSheetCoordinatorDataSource`

    public func sheetPositions(_ availableHeight: CGFloat) -> [CGFloat]{
        return [0.2, 0.7].map{$0*availableHeight}
    }
    
    public func initialPosition(_ availableHeight: CGFloat) -> CGFloat{
        return availableHeight*0.2
    }

and set breakpoints.

    extension UIViewController: UBottomSheetCoordinatorDataSource{}

adds the methods to all UIViewController.

I set the SheetViewController as dataSource before adding it:

        sheetCoordinator.dataSource = transitPlanViewController
        sheetCoordinator.addSheet(transitPlanViewController, to: self, didContainerCreate: { container in
            let f = self.view.frame
            let rect = CGRect(x: f.minX, y: f.minY, width: f.width, height: f.height)
            container.roundCorners(corners: [.topLeft, .topRight], radius: 10, rect: rect)
        })

Whatever I do, breakpoints show that always the methods of the default implementations are called, not the methods in the SheetViewController.
The reason to implement it in the SheetViewController is because the SheetViewController knows the size of the data it displays.

What do I have to do that my implementation is called?

I try to do what #33 suggests.

In the examples, there is no `UIViewController` that implements this methods.

**Comment by GerdC** [comment]
I have a workaround: using a proxy class that asks the ViewController.

I still think this is an undesired behaviour, but it is possible to get around it, so this issue has low priority.

**Comment by OfTheWolf** [comment]
@GerdC The issue is `extension UIViewController: UBottomSheetCoordinatorDataSource{}` so you cannot override it from your viewcontroller. This is intended for default behaviour but it has cons like your case. You should use it by creating new datasource class. See [MainViewController.swift#L71](https://github.com/OfTheWolf/UBottomSheet/blob/master/Example/UBottomSheet/MainViewController.swift#L71). Or you can modify the `public init(parent: UIViewController, delegate: UBottomSheetCoordinatorDelegate? = nil) ` by adding an extra datasource parameter. and remove  `extension UIViewController: UBottomSheetCoordinatorDataSource{}`. so u will be required to implement datasource everytime u create an instance of UBottomSheetCoordinator.
